### ISSUE TITLE
Changing capture Location

### ISSUE THREAD

**Issue by alwiebe1990** [not-implemented/raspicam-timelapse#17]
First of all i realy like your software. Works realy great.

It would be an amzing feature when you can change your capture location to an external drive. Like an external harddrive or thumb drive.

**Comment by not-implemented** [comment]
Thank you, cool, you are the first "external" user of raspicam-timelapse outside of our currently running timelapse-project :-)

You can currently change the capture folder in raspicam-timelapse/config/timelapse.json (when the node server is not running). When I have the time, I'll add an option for it (and some more like changing username/password) to the GUI, so this can easily be changed.

I leave the issue open for that.

**Comment by not-implemented** [comment]
Option "Capture path" (and some more) are now implemented in GUI (Commit b1761ec1195a9a6a65896a488645fa2ca1a6b9c2).
