### ISSUE TITLE
Timelapse sequence start

### ISSUE THREAD

**Issue by luisbarreto** [not-implemented/raspicam-timelapse#18]
Hello,

This is not a real issue with Raspicam-Timelapse, but a feature request.
I've got Raspicam-Timelapse working with RPi 3 straight-away without any issues.
Is there any way to adjust:

`output: config.capturePath + '/' + config.captureFolder + '/img_%04d.jpg',`

so the sequence starts with `img_0000.jpg` and not with `img_0001.jpg`?

I am using OpenMAX gstreamer plugin (gst-launch-1.0) to rely on RPi GPU processing power to speed-up the time needed to get the video and this plugin needs the sequence to start with `...0000` (zeros) and not with `...0001`.

**Comment by not-implemented** [comment]
I had a look into the raspistill source (the underlying program we use for capturing) - there is an undocumented "-framestart" option (implemented here: https://github.com/raspberrypi/userland/pull/282/files) to set the first frame number - default is "0" and then incremented for the first frame. Unfortunately it is parsed as unsigned int, so it cannot be initialized with "-1" which would be needed to have "0" for the first frame.

As the filename-generation is done inside raspistill and not here, we can not implement this currently, sorry.
