### ISSUE TITLE
Set preview image ratio based on user settings

### ISSUE THREAD

**Issue by Lippe** [not-implemented/raspicam-timelapse#24]
Currently the preview image is displayed in a 16:9 default ratio. Although this will be the standard most of the times, the preview image should respect the user's settings. This can be done by overriding the custom property "--bs-aspect-ratio" in JS (currently set as inline-style: --bs-aspect-ratio: calc(9 / 16 * 100%)).

**Comment by not-implemented** [comment]
Implemented with commit 8f9923b28ac87132593edbdc431ec97ce79865ac
